POST http://localhost:8080/api/shorten HTTP/1.1
content-type: application/json

{"url":"test.test/http"}



###

POST http://localhost:8080/ HTTP/1.1
content-type: text/plain

http://test.test/http

# 201 (Created) 1
# 404 (Not Found)

###

POST http://localhost:8080/ HTTP/1.1
content-type: text/plain

http://localhost:8080/thirdurlposting

# 201 (Created) 2
# 404 (Not Found)

###
POST http://localhost:8080/ HTTP/1.1
content-type: text/plain

http://localhost:8080/thirdurlposting

# 201 (Created) 2
# 404 (Not Found)

###


GET  http://localhost:8080/1 HTTP/1.1
@no-redirect

# 200 (OK)
# 404 (Not Found)

###

GET  http://localhost:8080/0 HTTP/1.1

# 200 (OK)
# 404 (Not Found)

###


POST  http://localhost:8080/2 HTTP/1.1
content-type: text/plain


# 200 (OK)
# 404 (Not Found)